apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy73
  labels:
    app: autodeploy73
  namespace: namespace-workflow-1714480937466
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy73
  template:
    metadata:
      labels:
        app: autodeploy73
    spec:
      containers:
        - name: autodeploy73
          image: acrworkflow1714480937466.azurecr.io/image-workflow-1714480937466:latest
          ports:
            - containerPort: 5000