apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployXX73
  labels:
    app: autodeployXX73
  namespace: namespace-workflow-1714472041842
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployXX73
  template:
    metadata:
      labels:
        app: autodeployXX73
    spec:
      containers:
        - name: autodeployXX73
          image: acrworkflow1714472041842.azurecr.io/image-workflow-1714472041842:latest
          ports:
            - containerPort: 5000